# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "master" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.1.2",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-master.sh"
  end

  config.vm.define "logger" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.1.3",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-logger.sh"
  end

  config.vm.define "chunk1" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.1.4",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-chunk.sh"
  end

  config.vm.define "chunk2" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.1.5",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-chunk.sh"
  end

  config.vm.define "client1" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.10.2",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-client.sh"
  end

  config.vm.define "client2" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.10.2",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-client.sh"
  end

end
