# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "master" do |master|
    master.vm.box = "base"
    master.vm.network "private_network", ip: "192.168.30.2",
	virtualbox__intnet: "mynetwork"

    config.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-master.sh"
  end

  config.vm.define "logger" do |logger|
    logger.vm.box = "base"
    logger.vm.network "private_network", ip: "192.168.30.3",
	virtualbox__intnet: "mynetwork"

    logger.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-logger.sh"
  end

  config.vm.define "chunk1" do |chunk1|
    chunk1.vm.box = "base"
    chunk1.vm.network "private_network", ip: "192.168.30.4",
	virtualbox__intnet: "mynetwork"

    chunk1.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-chunk.sh"
  end

  config.vm.define "chunk2" do |chunk2|
    chunk2.vm.box = "base"
    chunk2.vm.network "private_network", ip: "192.168.30.5",
	virtualbox__intnet: "mynetwork"

    chunk2.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-chunk.sh"
  end

  config.vm.define "client1" do |client1|
    client1.vm.box = "base"
    client1.vm.network "private_network", ip: "192.168.30.12",
	virtualbox__intnet: "mynetwork"

    client1.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-client.sh"
  end

  config.vm.define "client2" do |client2|
    client2.vm.box = "base"
    client2.vm.network "private_network", ip: "192.168.30.13",
	virtualbox__intnet: "mynetwork"

    client2.vm.provision "shell",
   	 inline: "/vagrant/setup.sh && /vagrant/setup-client.sh"
  end

end
